### ISSUE TITLE
Out of memory error

### ISSUE THREAD

**Issue by stephendparker** [DerPopo/UABE#111]
Trying to open an asset file and the app hangs until it runs out of memory - wondering if there is some kind of recursive loop it gets stuck in.  I believe it is one of the newer file formats. Thanks for the great tool!

**Comment by DerPopo** [comment]
Usually that happens when a file format is different than what the program thinks and the program sees some "random" data as the size of a buffer or list, causing it to try to allocate huge amounts of memory.
Which Unity version does the .assets file have (it's text in the first 32 bytes of the file formatted like "5.5.0f3", you can use a hex editor or even notepad on small files to find it out). Also, are you using the current release 2.1c?

**Comment by stephendparker** [comment]
I'm using the latest version of the program.

Here is the file (quite large):
https://www.dropbox.com/s/1w3fdvzx17zjqm6/resources.assets?dl=0

Your tool is awesome btw. Thanks for doing all that free work

**Comment by DerPopo** [comment]
I can open that file fine. Are there large files next to the resources.assets? Maybe the file list is large enough to run out of memory (and building the file list is relatively slow, partially due . Opening resources.assets alone makes UABE require 307MB. Depending on the amount of system RAM and if 32 or 64bit is used, it's possible to reach the limits.

**Comment by stephendparker** [comment]
Thanks for pointing this out.  Yes, there are a number of other files next
to it.  Did not realized it read from them too.  I will try with it in its
own folder.  I have 16gb ram..the file used to open fine (take maybe 10s to
open) now it hangs and takes about 30-40 min before I run out of
memory...why I'm thought there might be something recursive going on but
like u said maybe other file causing it with incorrect allocation.

**Comment by stephendparker** [comment]
you can close this issue it is not working
