### ISSUE TITLE
Export bundles to assets in API

### ISSUE THREAD

**Issue by nesrak1** [DerPopo/UABE#113]
I had assumed it was AssetsBundleFile but Unpack apparently is for compressed bundles, right?
I don't know what else to use.

**Comment by nesrak1** [comment]
And to add to it, how to view the scenes inside BuildSettings in the globalgamemanagers file

**Comment by DerPopo** [comment]
Unpack is to decompress bundle files. 
Depending on the bundleHeader3.fileVersion (same as bundleHeader6.fileVersion), the info on the bundle entries is located in assetsLists3 or bundleInf6.
In case of assetsLists3, go through each assetsLists3->ppEntries (count entries) and pass assetsLists3->ppEntries[i] to MakeAssetsFileReader, in case of bundleInf6, go through each bundleInf6->dirInf (directoryCount entries) and pass &bundleInf6->dirInf[i] to MakeAssetsFileReader.
Call assetsFile.MakeAssetsFileReader by 1. passing the original AssetsFileReader as used for the Read call, 2. passing a pointer to a local LPARAM variable that has the original reader parameter value (e.g. LPARAM readerPar = originalReaderPar; then pass &readerPar) and 3. the pEntry as described. Then store the return value to get the new AssetsFileReader.
To export the .assets file accessible through the new AssetsFileReader/parameter pair, you should read chunks of it into memory and write them to disk. The amount of bytes to write is specified in AssetsBundleEntry::length (version 3) or AssetsBundleDirectoryInfo06::decompressedSize.

The BuildSettings structure often changes between minor Unity releases. Various issues such as invalid buffer lengths can arise from such changes. Usually it hangs for a long time recursively counting the required size of memory buffers for the AssetTypeValueFields, AssetTypeValues and data buffers as it has to go through e.g. 695510106 items. If the user waits for it to complete (hopefully not), it would usually fail because the memory is insufficient. Maybe I should add a break as soon as it goes past the file end, only reading 0s?
For the ResourceManagerFile class, which parameters do you use? I haven't seen it change except in major .assets file format changes. filePos needs to point to an int initialized to 0. bigEndian should be set to AssetsFileHeader::endianness. data and dataLen point to the ResourceManager asset data in memory.

**Comment by nesrak1** [comment]
ResourceManagerFile is fine. I meant that I tried using ATI with resource manager but that froze too until I found out that the api had ResourceManagerFile which worked.

**Comment by DerPopo** [comment]
In case it's the reason for the crash, you need to use `ati.GetBaseField()->Get("m_Name")->GetValue()->AsString()` and optionally check that ati.GetBaseField()->Get("m_Name")->GetValue() != NULL.

I'm quite busy right now but you can take a look at the sample plugin code I released below the API. It creates an AssetTypeInstance of TextAsset. It uses the plugin interface to get the template field though.

**Comment by nesrak1** [comment]
I haven't seen your examples yet so I'll check them out later.
I guess I forgot about asString in my example but it _is_ in my actual code.
Regardless, before I even touch the cout code it crashes

**Comment by nesrak1** [comment]
I don't want to clutter up the issues again so I'll just put all of my problems that I have right now here.
1. What do I do about BuildSettings not reading?
2. I have a GameObject. There is only one MonoBehaviour attached to this GameObject, and I can successfully tell which is the MonoBehaviour. Then I used this code:
```
//atvf is the array
AssetFileInfoEx* assetsFileInfoD = assetsFileTable.getAssetInfo((QWORD) atvf->Get((unsigned long)i)->Get("second")->Get("m_PathID")->GetValue()->AsInt64()); //When I do assetsFileInfoD->index it returns the correct ID.
AssetTypeInstance atid(1, &pBaseField, AssetsReaderFromFile, (LPARAM) pFile, false, assetsFileInfoD->absolutePos);
```
But whenever I try to get m_Script, it fails.
I made a for loop with `std::cout << atid.GetBaseField()->Get((unsigned int)j)->GetName();` and it outputted `m_Component, m_Layer, m_Name, m_Tag, and m_IsActive`. That's GameObject stuff, not MonoBehaviour.
