### ISSUE TITLE
UABE crashes when I open multiple assets

### ISSUE THREAD

**Issue by evildog1** [DerPopo/UABE#122]
When i open multiple assets or all crashes, it just crash/stopped working. Opening all assets does work on some games but not always. This is annoying because I need to find AudioClips in all assets.

I got this error when I open sharedassets29.assets.split0
![image](https://cloud.githubusercontent.com/assets/8687585/24919995/dd9b7c90-1ee5-11e7-8412-f93be14e1b90.png)

Here is the RAR file that contains all assets
https://mega.nz/#!iJwzySJb!wEZ_GeGHurMylmBT9jF8HGZTigMpjXpXk1oRmXVM7Rc

**Comment by DerPopo** [comment]
I've forgotten to verify the files except the first selected so .resource files are treated like an .assets file. It will be fixed in the next release.
As a workaround, move the .resource and the .resource.splitX files into another directory before opening the .assets (don't select more than ~2000 including all associated splits because of a fopen limitation). Once it's opened, you can move the .resource files back to the same folder and extract the AudioClips.

**Comment by evildog1** [comment]
Oh ok. I moved them in another directory and it works.
When I extract AudioClips, I got this error
![image](https://cloud.githubusercontent.com/assets/8687585/24956110/69ff75ba-1f86-11e7-9847-03affa3bd431.png)

**Comment by DerPopo** [comment]
Before extracting AudioClips, you must move the files back into the same folder.

**Comment by evildog1** [comment]
Sorry I missed that because I was lazy to read
