### ISSUE TITLE
Request: Ability to compress bundle again

### ISSUE THREAD

**Issue by imxzjv** [DerPopo/UABE#149]
When opening my bundle i get the prompt 'This bundle file is compressed!" and i unpack it. Then after modifying the file i need to return it to its compressed form. According to the documentation this is a form of LZMA/XZ but obviously with some Unity special sauce and therefore normal compression tools wont work. Any chance of getting this feature to return bundles into a compressed state that Unity can read? Also is there any way to test pre-release beta versions? im interested, let me know. Thnx!

**Comment by DerPopo** [comment]
Unity does use normal LZMA or LZ4 (or the compatible LZ4HC) compression but the bundle files contain a header in front of that, a potentially compressed entry list and a variable number of data blocks. The compressed LZMA blocks don't have the normal [.lzma header](https://svn.python.org/projects/external/xz-5.0.3/doc/lzma-file-format.txt) since the decompressed size already is in Unity's custom headers.

I have implemented experimental compression support. Compressing bundles with LZMA works so far but I haven't succeeded compressing blocks with the LZ4 library without reading the whole input file to memory so far.

**Comment by DerPopo** [comment]
Closing this issue since UABE 2.2 is out. Feel free to open a new issue if you have further questions or requests.
