### ISSUE TITLE
.assetbundle incompatibility

### ISSUE THREAD

**Issue by welovekah** [DerPopo/UABE#156]
Trying to decode some .assetbundle files. I'm not sure the exact Unity version being used for the game, but since their [Twitter](https://twitter.com/racjintweet?lang=ja) launched in May 2015, I'm guessing it uses something close to 3.5.

Attempting to open one of the .assetbundle files in UABE results in the error message 'Unable to read the bundle file! (Invalid file or unknown version?)' as expected if the file is of an outdated version or is encrypted.

Opening the raw file, it looks like it might be encrypted, but I don't see an obvious headers in a Hex Dump of the contents.

Any ideas on what I should try next, here? Is there any other debugging I can do through UABE to figure out why the file isn't compatible?

[Here's one of the files in question.](https://drive.google.com/open?id=0B2HSXxTsSMeRSFpHYnNWMkE4VFk)

**Comment by DerPopo** [comment]
It seems like they have encrypted/obfuscated/whatever the beginning of the bundle header.
In case of this file, it can easily be restored with a hex editor. Replace the first 0x97 bytes (offsets 0x00 through 0x96) with the following :
`55 6E 69 74 79 57 65 62 00 00 00 00 03 33 2E 78 2E 78 00 34 2E 36 2E 39 66 31 00 00 00`.
Repacking the file won't be that simple because the current release version of UABE doesn't support recompressing bundles, and uncompressed bundles have a different header.

**Comment by welovekah** [comment]
Thanks, that worked perfectly. I don't have any need to repack, just datamining, so this fits my needs just fine.
