### ISSUE TITLE
MonoBehaviour type and a couple of issues

### ISSUE THREAD

**Issue by joyello** [DerPopo/UABE#16]
Thanks a lot for the new version!

Do you have any idea how to open MonoBehaviour type of files? 
Look at this for example: http://www.filedropper.com/aa_3 . It's easy to understand what's going on inside the file, but sometimes it's hard to read (when values are present).

Additionally, I have to report that using the plugin to export Texture2D makes the app crash, at least for most of the files.

P.S. Any chance for animations to be opened in the future?

**Comment by DerPopo** [comment]
MonoBehaviour files are specific to each class (and always contain some variables like which class they belong to). I'll look into creating an import function for type databases exported from a game assembly.

The Texture2D plugin requires the correct type database for the .assets' version (simply because it would otherwise interpret e.g. the first 4 bytes of the image as the image size). If it crashes, just replace the classdata_0E with classdata_0E.5.0.1f1.

**Comment by angelasvv** [comment]
![t](https://cloud.githubusercontent.com/assets/7068677/14877118/0c94a392-0d4d-11e6-8fc3-4e497a1107fd.jpg)
I have the same problem.Old files are not packed. Now that the new file is packed, I want to extract the new file.
This is the source file：
![o](https://cloud.githubusercontent.com/assets/7068677/14877169/6a9fbf9e-0d4d-11e6-8c01-ff4db097dc77.jpg)

how to  export?
Can I edit Databa for export?

**Comment by DerPopo** [comment]
If you haven't extracted the .assets file out of the bundle, do that. Then, import the new file and save to another .assets file (it won't show the new data before you reopen it). If it worked, import the .assets file to the bundle and save the bundle.

**Comment by angelasvv** [comment]
Thx for replay,I have extracted the .assets file.
but I need extract the files .ssax of .assets file (this files use to other software,that is Animation scripts)
