### ISSUE TITLE
Unable to open more than 2045 files

### ISSUE THREAD

**Issue by Titansmasher** [DerPopo/UABE#167]
Whenever I attempt to open or reference more than 2045 files (I assume, the file ID listed never exceeds 2044, I guess its related somehow to 2048) all seems fine until I attempt to export all the Texture2D images to a folder, at which point it hangs for about a minute before stopping the operation. No images are extracted.

When trying to open smaller amounts of files at once, it works fine (using counts of ~ 1800 at a time) however this leads to duplicate files and requires processing by another application to remove duplicates and sort out the namings.

Would an increase on this limit be possible (I have 4700 files to go through, so perhaps to ~ 8192 if my guess at it being powers of 2 related is correct), or if not, some message that indicates what the problem is rather than a silent and lengthy failure.

**Comment by DerPopo** [comment]
Windows' fopen has a limit of 2048 opened files (effectively 2045 because of stdin, stdout and stderr afaik) that can't be increased any further. UABE 2.2 will bypass that by temporarily closing other files. I could use Windows' CreateFile instead, but I don't think opening 8000 handles is the right way to solve this.

**Comment by DerPopo** [comment]
Closing this since UABE 2.2 should have fixed this. Please open a new issue if it still has issues opening many files.
