### ISSUE TITLE
A slight change on packing

### ISSUE THREAD

**Issue by jack980517** [DerPopo/UABE#170]
A game that was just released several days ago has a new method of packing.
There's now a `data.unity3d` file, which is an asset bundle containing everything previously in the `Data` folder except the `Managed` folder, `Raw` folder, `unity default resources` and `resources.resource`. (That game has no raw assets, so I couldn't confirm if stuff in the `Raw` folder was also in `data.unity3d`, but I don't think they would be in there.)
UABE as of 2.2 beta1 (The forum post is still not updated, so I can't test 2.2 stable) can properly read `data.unity3d` itself, but can't extract audio from `resources.resource`. It's now necessary to detect streaming data files from outside the asset bundle.

**Comment by DerPopo** [comment]
Indeed, new Unity versions have an option to package all .assets files into a single compressed bundle. 
I will add support for such streamed data references with 2.2 beta2, along with 2017.3 support.

**Comment by jack980517** [comment]
Could you also modify the program to directly read lz4-compressed bundles instead of fully decompress them first? With this new packing method, the compression ratio is really low, about 15% for the new game I mentioned.

**Comment by DerPopo** [comment]
The issue is that you can't read data at specific locations in a LZ4 or LZMA compressed file without decompressing the preceding data. While LZ4 is fast, having to read and decompress the whole file still adds a lot of overhead. Caching the whole decompressed file in RAM isn't an option either.
Besides, working with compressed data would cause a lot of hassle besides performance issues, such as the need of compressed stream reading with caching heuristics and custom LZ4&LZMA decompress code for an efficient implementation.

Caching the decompressed bundle on the disk has the only disadvantage of having to wait until the file is written. When saving, a complete recompression of the file is required in either case.

**Comment by jack980517** [comment]
All right. Thanks for answering.
