### ISSUE TITLE
Open-sourcing the code

### ISSUE THREAD

**Issue by FrankBro** [DerPopo/UABE#19]
I've been trying to extract some assets from a game with mixed results with your tool. However, your tools has been able to do much more than any other tools I've seen (most will crash/error out). I would like to contribute to it and fix my issues with it if possible.

In my case, extracting some texture2d give bad results. I've tried "edit" and changing the format to no avail.

**Comment by DerPopo** [comment]
I am not planning to make it open-source but I'll look into your issue.
What kind of bad results do some Texture2D give? What type database (for U5 the default one, the old 5.0.1 one or 5.1.1) do you use and what Unity version does the game have? The plaintext Unity version is at the first 32 bytes of each .assets or bundle file.
There have been some problems extracting Texture2D files because of some changes in Unity 5.2.x's asset format that are not compatible to previous versions.

**Comment by FrankBro** [comment]
It's the assets from the game "Amazing loot grind". It's pixel art. The extracted images look like pixel art but the pattern makes no sense and the colors are wrong. Trying multiple format will move the pixels around but still not produce an image that makes sense. I grabbed everything from the apk. In it, you see a bunch of images with clear names like "chest 5-1". I just had to merge a .assets.0 and 1 together to get them.

**Comment by 0x900x90** [comment]
As i allready wrote, the problem is in RGBA4444 decoder. Some channels are swapped. I don't know wich.

Here is the assets file from the game.
http://www83.zippyshare.com/v/vxHRM91j/file.html

**Comment by DerPopo** [comment]
It seems like it's not actually RGBA4444 but BARG4444 instead (or there is a color channel error somewhere else). RGBA32 is RGBA32 so I don't understand why it's different there.

**Comment by 0x900x90** [comment]
Maybe it is unity bug then? Because Unity Assets Explorer shows me rgba4444. 13 is RGBA4444 in Unity 5? In raw extracted texture i see 0x0d format id.

**Comment by DerPopo** [comment]
Should be fixed in 1.8.1. Can you confirm that?

**Comment by FrankBro** [comment]
Yes perfect, thank you very much.
