### ISSUE TITLE
Empty dumps (Bad Piggies assets)

### ISSUE THREAD

**Issue by FunnyGameNS** [DerPopo/UABE#218]
When trying to dump any of Bad Piggies' assets it just gives an almost empty file.
Raw asset exporting is working.

Asset + its dump: https://drive.google.com/file/d/1sBQnAriJwOq7znO3MfoVqWdQL1AHgn_8/view?usp=sharing

Any solution pls?

**Comment by DerPopo** [comment]
These TextAssets actually aren't text, which causes issues with the dumps. Use the TextAsset plugin on these assets instead, which handles text files correctly.

**Comment by FunnyGameNS** [comment]
> TextAsset plugin on these assets instead, which handles binary files correctly.

But do i need to keep original file size?

**Comment by DerPopo** [comment]
The TextAsset plugin has no issues with different file sizes, as long as the modified file is correct (i.e. the same format the game expects). If you want to edit text embedded into the file, you need to update the according lengths. 

With a hex editor (e.g. HxD), you can see that every text segments starts with `EF BB BF` (text encoding marker for UTF8) and has a four byte length field before that (counting the length of the total text segment in bytes, starting with the EF BB BF marker). The number is in little-endian, so if it's `A9 09 00 00` the hexadecimal number you're looking at is 000009A9 (reversed byte order). Every ASCII character will be 1 byte, so every additional character will usually increase that number by 1. 

However, I'm not totally sure if that's everything you need to change since the binary file format might also have absolute file positions or other things that need to be adapted in order to change the text length. The game code that reads the file should be easy to decompile using tools such as ILSpy or dnSpy, unless the game uses IL2CPP or the code is obfuscated. It's usually located in Assembly-CSharp.dll or Assembly-CSharp.firstpass.dll.
