### ISSUE TITLE
No Support for Unity 2018.2.0f2

### ISSUE THREAD

**Issue by xojnowns** [DerPopo/UABE#220]
UABE is unable to extract files from Unity 2018.2.0f2
![unknown 2](https://user-images.githubusercontent.com/41763296/43293895-fe5e8c92-9112-11e8-8226-10d003e5e399.png)

**Comment by 0x900x90** [comment]
I think we have to find the way how to extract type database from unity or maybe from assets with type description in their headers.

For example 5.4.0f3 type database is not enough for all 5.4.* family. I can't export sprites from 5.4.1 asset file with it. I'm ready to help you with creating more type databases. I just don't know how i can help.

**Comment by DerPopo** [comment]
I might look into using the type hashes every Unity 5+ file should have instead of the Unity versions, which should help detecting incompatible type information. Older Unity versions either embed the full type information or none, so the version numbers still have to be used in that case.

I'm currently extracting the type information by updating the extractor tool for a specific Unity 32bit development player and starting it on a sample project. The tool hooks into some engine functions to find all types (TypeManager::RegisterType) and after the engine initialization, it generates objects of each type and calls GenerateTypeTree on them. The symbols of the development player help finding these functions, but it's still not fully automatable since these things change quite often (e.g. different function parameters, changes in structures, refactoring, etc.).

I'll look into publishing it to a repository, but don't expect very clean code since it's full of #ifdef statements to make it compilable for all the supported Unity versions since 3.4.
