### ISSUE TITLE
Edited AssetBundle Wrong Build Version

### ISSUE THREAD

**Issue by dastrdly6585** [DerPopo/UABE#230]
After uncompressing an asset bundle, I've tried exporting a text dump of a Monobehaviour, editing it, reimporting it, and then saving the edited bundle.  Unfortunately, the game throws this error in its log file:
"ERROR: The AssetBundle 'gamedatabase.unity3d' can't be loaded because it was not built with the right version or build target."

The version of the asset bundle produced by UABE after uncompression can be loaded fine by the game as long as no edits are made.  In contrast, saving after simply reimporting an unedited version of the exported text dump of a Monobehaviour asset results in a bundle which the game can't load.  Edited bundles can be opened fine by UABE and modifications that were made are correctly saved.

Is this a fixable issue with UABE where the edited bundle can be set to be "built" by the right version and with the right build target?

The Unity AssetBundle type is 2018.1.0f2.
The game uses IL2CPP.
The OS is Windows 10 x64.
I am using UABE 2.2beta4.

As an addendum that may or may not be useful: each AssetBundle file for this game has an associated .manifest file. Each .manifest file has a CRC and two hashes (AssetFileHash & TypeTreeHash).  I am unsure if the game actually does a checksum comparison using these files.

I can provide a link to the AssetBundle if you need a copy to troubleshoot this issue.

Edit: I found [this forum post](https://forum.unity.com/threads/asset-bundle-cant-be-loaded-because-it-was-not-built-with-the-right-version-or-build-target.376688/) which indicates that if a game is compiled using IL2CPP (rather than .NET), its asset bundle is built using a different serialization.  Perhaps this is the issue, since I'm not sure UABE currently accounts for this difference.

Edit 2: Since renaming the associated manifest file did not prevent the game from starting up with the original AssetBundle file, the game almost certainly does not make use of the manifest file in a checksum comparison.  I also determined something else that might help: the game also has a resources.assets file that can have TextAssets replaced without problem with UABE.  The AssetBundles which currently can't be edited correctly are under the subdirectory "StreamingAssets/ResourceBundles" of the game's data folder.

Edit 3: Here are screenshots of the first few bytes of the AssetBundle in question.  It can be clearly seen that the Original version (unedited & uncompressed) is vastly different from the UABE saved version (unedited & uncompressed).

Original (unedited & compressed): 
![gamedatabase_header_original](https://user-images.githubusercontent.com/13990010/46048054-7bb85a80-c0f5-11e8-9138-d20013890e1f.jpg)

Original (unedited & uncompressed):
![gamedatabase_header_uncompressed](https://user-images.githubusercontent.com/13990010/46048062-8a9f0d00-c0f5-11e8-8c7f-624d293d3245.jpg)

UABE Saved (unedited & uncompressed):
![gamedatabase_header_uabe-saved](https://user-images.githubusercontent.com/13990010/46048070-94287500-c0f5-11e8-91d3-c40bf3d8ddab.jpg)

**Comment by dastrdly6585** [comment]
Upon further investigation, I have determined that each AssetBundle file this game uses has an associated .manifest file.  It may be that the game is checking the CRC and/or the hashes listed in the .manifest and finding a mismatch, causing the game to not accept the modified AssetBundle.  Is there any means of determining the CRC/hash of the edited AssetBundle such that the .manifest file can be edited for the game to accept the edited AssetBundle?

**Comment by DerPopo** [comment]
Sorry for the late response. I'm looking into this and seemingly related issues ( #237 #239 ). It'd be great if you could give me a link to an affected file.

**Comment by dastrdly6585** [comment]
Sure, here's the link to the bundle in question:

[https://drive.google.com/open?id=1Sld8krPhbeZpBehOBiu0Bc5yoDdElVyS](https://drive.google.com/open?id=1Sld8krPhbeZpBehOBiu0Bc5yoDdElVyS)

If you'd prefer a file uploading website other than Google Drive, please let me know.

**Comment by DerPopo** [comment]
I suspect it's related to UABE not taking the preload list (inside the serialized CAB file) into account when saving the file, so the assets are stored in a different order.

There are a few other differences between the modified and the unmodified files, which I suspect are not the reason for the problem, since the only relevant change in the files from #237 is the asset order as mentioned above.
The other differences are (i) the data block descriptors of the bundle (all those 10-byte entries of 02 00 00 00 02 ...), because the compressed file had lots of smaller compressed chunks to speed up random access in the file, (ii) the stream flags of the blocks which I also should take a look at for other reasons and (iii) the order of the bundle entries (which was not intended and will be fixed, but it still shouldn't invalidate the file).

On a related note, when I experimented with such small compressed chunks that also end/start in the middle of assets, the Unity Player randomly read corrupted data out of nowhere at some of these borders. Obviously, they have fixed that issue since they are now generating such bundles themselves.

**Comment by dastrdly6585** [comment]
Just did a simple test modifying one MonoBehaviour asset and the saved asset bundle was successfully loaded by the game.  Since that suggests the issue has been solved, I'll go ahead and close it.  Thanks for your hard work on UABE!
