### ISSUE TITLE
Auto Installer Fails on Writing/Modifying Bundle File

### ISSUE THREAD

**Issue by korvyr** [DerPopo/UABE#231]
So I'm modding a game that has a compressed data bundle.

`data.unity3d`

All goes well with the modding itself, and generating the installer executable is fine, but when running the installing executable it simply crashes (disappears, process ends, no error) when trying to modify/write to the decompressed bundle file.

`data.unity3d.decomp` appears, then the exe installer moves to writing/modifying and then crashes with no error.

**Comment by DerPopo** [comment]
If you export the package file of the mod to a package file (emip), does UABE itself crash when saving the changes imported from this emip file (File->Load Package File)?

I suspect there may be an issue with either reading the installer package file embedded into the installer, or the package file itself.

I did find a bug that causes a crash if the bundle write function wants to print a warning or error message (forgot to check if the error logger is null). That specific bug should be fixed in this hotfix :
[AssetsBundleExtractor_2.2beta4_hotfix2.zip](https://github.com/DerPopo/UABE/files/2465538/AssetsBundleExtractor_2.2beta4_hotfix2.zip)
There also is a new console command that uses the same code as the installer :
```AssetBundleExtractor applyemip <.emip file> <base directory>``` (it should output the messages from the bundle writer, if there are any).

**Comment by korvyr** [comment]
It simply fails still with the new version, leaving nothing behind. Even when just trying to load the emip and save, it crashes out with no error. The console command doesn't seem to exist for the version I just pulled from Github.

**Comment by korvyr** [comment]
Your hotfix seems to have fixed it. Thanks mate!
