### ISSUE TITLE
How to get unity's asset bunddle version?

### ISSUE THREAD

**Issue by artemking4-Projects** [DerPopo/UABE#233]
How to get unity's asset bunddle version?

**Comment by DerPopo** [comment]
UABE currently does not show this, but you can easily find it out using a hex editor, since it's stored in the file header (just look for version strings like 2018.1.0f3 or 5.0.1p6 at the top). 

In case the game creates output_log.txt files, they should also contain the engine version of the player.

**Comment by artemking4-Projects** [comment]
Thank
