### ISSUE TITLE
Strange problem

### ISSUE THREAD

**Issue by jack980517** [DerPopo/UABE#237]
I'm dealing with a MonoBehavior, and I want to change some data in it.
However, even if I only change two float numbers in it, the game crashes. I can see the game reporting a NullReferenceException to Unity Analytics, but I can't see the traceback info.
Back in December 2016, with an older version of the same game (Unity 5.4.3p2) and the then-latest version of UABE (2.0), I succeeded. But now it fails (Unity 5.6.5f1, UABE 2.2 beta4). I'm not even sure if this is because the game changed or because UABE has issues.
Attached is the asset bundle in question, before and after I changed it. Please look into it...
[what.zip](https://github.com/DerPopo/UABE/files/2476060/what.zip)

**Comment by DerPopo** [comment]
The only difference besides slightly different padding (which shouldn't be an issue since the offsets are correct) is how the assets are aligned. 
The original file has the MonoScript and AssetBundle assets stored before the MonoBehaviour assets, which is a different order than the asset list (which, in turn, is ordered by the Path IDs). In the modified file saved by UABE, the order of the asset list is used instead.
The preload list inside the .assets file specifically lists the MonoScript assets, so I suspect Unity wants these assets stored before the others.

**Comment by jack980517** [comment]
Thanks for the information. It's great that you figured something out. Looking forward to a fix!
