### ISSUE TITLE
support 5.3.2f1

### ISSUE THREAD

**Issue by MakuraYami** [DerPopo/UABE#27]
As title says, newest version is not supported yet.

Please add support for it :)

**Comment by chrsmith** [comment]
:+1: I used to use github.com/ata4/disunity for cracking open Unity asset bundles, but since the latest patch to the game's client Disunity can no longer recognize the file. I tried UABE, but it fails too. Hopefully the Unity changes to 5.3.2f1 aren't too difficult.

If the problem is well understood, I'm happy to help out if I can be of use.

**Comment by DerPopo** [comment]
LZ4 bundles already work in the current release, only LZMA ones don't. It already is fixed for the next one.
