### ISSUE TITLE
When I open the Extractor it opens up a movie player

### ISSUE THREAD

**Issue by jpboudreault** [DerPopo/UABE#294]
Is this expected?

![image](https://user-images.githubusercontent.com/1963065/62877739-b1f2ce80-bcf5-11e9-9f17-ba5ec6a96a64.png)

**Comment by jack980517** [comment]
`.exe` is the extension for Windows executable files. UABE is a Windows program. Judging from the screenshot you seem to be using Mac. To run Windows programs on Mac, you need Wine. Otherwise double clicking it would just open whatever `.exe` files are associated with on your computer, which seems to be a movie player.

**Comment by jpboudreault** [comment]
Thank you
