### ISSUE TITLE
Name format when export raw

### ISSUE THREAD

**Issue by Alice-Schuberg** [DerPopo/UABE#304]
![캡처](https://user-images.githubusercontent.com/39822140/65849504-cb270b80-e385-11e9-89c3-448bbf72f7b4.PNG)

When export raw
The name is stored as (Asset Name-Filename.Extension-Asset Path)
However, if the Asset Path is negative, the numbers will be different.

I need to know the correlation of these numbers

**Comment by jack980517** [comment]
This is due to the type mismatch of signed vs unsigned 64 bit integers.
Signed integer uses two's complement to represent negative numbers in memory. You can try it out using this [online demo](https://www.exploringbinary.com/twos-complement-converter/), specifying the number of bits as 64.
`-9222927786704351946` in two's complement is `1000000000000001100101000000101100001100011010000100110100110110`. Convert that back to decimal as an unsigned integer, you'll get `9223816287005199670`.

**Comment by jack980517** [comment]
If you don't want to understand two's complement entirely, just remember:
2^64-[absolute value of the negative number you see in the asset list]=[the positive number you see in the default file name]
eg. 2^64-9223816287005199670=9222927786704351946

**Comment by Alice-Schuberg** [comment]
> 2의 보수를 완전히 이해하지 않으려면 다음을 기억하십시오.
> 2 ^ 64- [자산 목록에 표시되는 음수의 절대 값] = [기본 파일 이름에 표시되는 양수]
> 예. 2 ^ 64-9223816287005199670 = 9222927786704351946

**Comment by Alice-Schuberg** [comment]
thank you very much!!
