### ISSUE TITLE
Extracting classdata from player.

### ISSUE THREAD

**Issue by 0x900x90** [DerPopo/UABE#34]
Some time ago you wanted to share the tool for extracting classdata from unity player. Do you still have plans to do this? Sometimes 4.5 classdata not enough to work with older unity assets.

**Comment by DerPopo** [comment]
The patterns to find the required functions in the player often change (sometimes also the parameters), which is why it isn't that simple to make it compatible to all versions. Maybe I'll make one that can use the debug symbols (of the debug player) instead but it would require downloading and installing a complete Unity release.

**Comment by 0x900x90** [comment]
OK. I understand. Did some RE works with unity player.
