### ISSUE TITLE
Can not export the file.

### ISSUE THREAD

**Issue by kiletw** [DerPopo/UABE#44]
FIle:http://www.rc.dmmgames.com/files/AssetBundles/5.3/Android/sound/cv_30444_000

File format: UnityFs 5.3.4f1

I try to extract wav files but when I press OK, nothing happens.

![Alt text](http://i.imgur.com/UAb0gge.png)

How can I do?

**Comment by DerPopo** [comment]
There's indeed a bug that makes opening resources from v6 bundle files always fail. It will be fixed with the next release.

As a temporary workaround, you can export both "CAB-" files (e.g. the normal one to exported.assets and the other one to exported.resource), then open the .assets file, export the dump of the AudioClip, open it, change archive:/CAB-.../CAB-....resource to e.g. exported.resource, import the dump, File->Save to e.g. exported2.assets and then use the plugin on the new .assets file.

**Comment by DerPopo** [comment]
It should be fixed with 2.0.
