### ISSUE TITLE
[Request] Search improvements

### ISSUE THREAD

**Issue by Devilin-Pixy** [DerPopo/UABE#48]
Below a few suggestions to improve the search feature:

- Have 'Continue search' under a key-bind (usually F3).
Currently repeating a search requires to open the menu to re-select 'Continue search'.

- Start a search from the current position, instead of having search start from the top by default.
This would be very helpful when there are a lot of matches.

- Ability to change search direction (up/down).

**Comment by DerPopo** [comment]
The continue search hotkey F3 is already in. If it doesn't work, it's possibly because of a anti-virus protector that doesn't like the (unusual) way through SetWindowsHookEx, even though it only checks the key presses on the asset list window. If that's the case, I'll switch to a more usual method.  
I'll work on the other suggestions.

**Comment by Devilin-Pixy** [comment]
I never realised it was already in as it doesn't show. Just tested and indeed F3 does work as I was hoping. You may however want to add it to the description in the menu as a suffix in parenthesis. Possibly for other hotkeys used as well.

**Comment by DerPopo** [comment]
It's added in 2.0.

**Comment by Devilin-Pixy** [comment]
Nice list of changes, wonderful work and much appreciated ;-)
