### ISSUE TITLE
Locating .unity files

### ISSUE THREAD

**Issue by delm959** [DerPopo/UABE#52]
Does the asset extractor recognise .unity files? I can't seem to find the following file...

![image](https://cloud.githubusercontent.com/assets/11843578/16360202/e974d592-3ba7-11e6-9769-4368e2d61709.png)

**Comment by DerPopo** [comment]
It looks like there should be such a GameObject in one of the bundle files. If there is no matching name in any of the bundles (type *7018Bundles_ab* in the search), it possibly is because there are multiple .assets files inside the bundle but only one has the name table. I can't tell if that's the real reason though.

**Comment by delm959** [comment]
It's quite hard to search as well because as I mentioned there are hundreds of asset files so searching through them takes forever. If I could open them all at once it would make searching a lot easier. Do you think you will implement that feature or will it be too much of a hassle? Great work by the way, has really helped me out a huge amount :)

**Comment by DerPopo** [comment]
I'll do some improvements for the command line so such things become easier.

**Comment by delm959** [comment]
Awesome! I will be eagerly waiting :)

**Comment by DerPopo** [comment]
2.0 is released. Multiple .assets files can be opened at the same time and the command line batch export commands also supports compressed bundles now.
