### ISSUE TITLE
Eksporting to .OBJ

### ISSUE THREAD

**Issue by KwarcPL** [DerPopo/UABE#64]
I'm trying to export mesh from asset (Unity 4.5) and program crashes. If you want to try it for yourself [here's my file](https://drive.google.com/open?id=0B90vRKE4dnmJNWxaSFhFbmw2aW8) ;)

**Comment by DerPopo** [comment]
Thanks for providing the data, it helped me improve the Unity 4 Mesh support.
Aside from that, the crash likely was because the type database provided by UABE (4.5) is too incompatible to the file (4.2). There will be one type database for each "semi-major" Unity build since 3.4, so that shouldn't be such a problem anymore.

**Comment by KwarcPL** [comment]
Friend from Xentax [are already helping with this files](http://forum.xentax.com/viewtopic.php?f=16&t=14808). Maybe it would be helpfull ;)

**Comment by DerPopo** [comment]
2.0 is released now.
