### ISSUE TITLE
Texture2D Plugin ResS in resources.assets

### ISSUE THREAD

**Issue by nesrak1** [DerPopo/UABE#73]
Editing a texture that has a reference to ResS only edits the assets file, it doesn't edit the ResS file (no change in game). Removing the reference to the ResS file causes errors as the game is loading.

EDIT: Apparently this happened to only a couple of specific textures in resources.assets
EDIT 2: It apparently decided to work all of a sudden, so all replaced textures don't crash the game.
It would still be cool though if ResS could be replaced instead of just adding a lot of space to the assets file and still keeping the old image in the ResS.

**Comment by DerPopo** [comment]
The problem with writing the changes to the .resS files is that the new texture can be larger or smaller than before, so removing the old one might require shifting all other textures and correcting the offsets in all Texture2D/Texture3D/Cubemap/AudioClip/... files that share that same file. If one of these file formats is changed, it would destroy all assets with such references (either because the asset itself is damaged or because it couldn't detect a reference to the .resS file).

**Comment by nesrak1** [comment]
If it was smaller, you could just add filler bytes of the same size...
But if it was larger... I see where you're going here... It would require a whole recompilation of the whole thing.

**Comment by nesrak1** [comment]
Here's how to do it manually I guess nesrak1/unturned-workshop-helper#1
