### ISSUE TITLE
Merge all split files together

### ISSUE THREAD

**Issue by evildog1** [DerPopo/UABE#97]
I'm looking for music files of the game but there are too make splits and i'm too lazy to re-edit the batch file again and again. Can you add an option to automatically merge all splits to sharedassets1.assets sharedassets2.assets and so on?

![image](https://cloud.githubusercontent.com/assets/8687585/21579126/aacc8420-cf9f-11e6-85bc-2284a5578508.png)

**Comment by DerPopo** [comment]
UABE 2.1 can open .assets.split0 files directly.
In case that doesn't solve your issue, could you explain your issue more precisely?

**Comment by evildog1** [comment]
I updated UABE 2.1 and it works now. Previous version couldn't open splitted file.

**Comment by DerPopo** [comment]
Is sorting the Type and searching with View->Search by name what you want?

**Comment by evildog1** [comment]
No, i wanted to search AudioClip in all files but i don't know if it is possible. This is the big problem for me and it will take an hour to find audio on all assets which would be boring. Tried Notepad++ file search trick but gives no results since all assets are compressed.

![image](https://cloud.githubusercontent.com/assets/8687585/21964875/5cda58bc-db54-11e6-8fed-d6cfcf4ae7de.png)

**Comment by DerPopo** [comment]
You can open multiple .assets files, just select all you want in the file open dialog. Then sort by Type and scroll to where the AudioClips are listed.
Note that UABE can only open a maximum of 2048 files at the same time (due to fopen limits), including all .assets and .assets.splitx. Even though it will show the asset list, it will be unable to export anything.
In Unity 5, .assets files without a .resource or .resS file don't have AudioClips.

**Comment by evildog1** [comment]
This saves me a lot of time. I didn't know that i can open multiple files
Thank you for help!
